# Perfil para execucao local (fora de container), banco subido via docker-compose
spring.datasource.url=jdbc:mysql://localhost:3306/gestao-academico?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=new123

jwt.secret=NuEDTlWWH/WitmbS7jdO2NiU0LICTGhNTY2rcqjq0adAzCS6kBRBgrkCmwXK+nReqh+Y9stgKEcHCnbZ3H213w==
jwt.expiration=86400000

cors.allowed-origins=http://localhost:4200
cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
cors.allowed-headers=Authorization,Cache-Control,Content-Type

logging.level.gestao.academico=DEBUG
